.PHONY: all gen_graphs

gen_graphs:
	mmdc -t forest -w 5948 -H 1028 -i resources/how_generate_ethereum_wallet.mermaid -o resources/Figure1_Gen_Ethereum_Wallet.png
	mmdc -t forest -w 4160 -H 1352 -i resources/magic_utc_file_pwd_to_priv.mermaid -o resources/Figure2_Magic_2FA_Get_PrivKey.png
	mmdc -t forest -w 4516 -H 5032 -i resources/how_generate_utc_file_simplified.mermaid -o resources/Figure3_Gen_Ethereum_UTC_JSON_File.png
