.PHONY: all gen_graphs

gen_graphs:
	mmdc -t forest -w 2974 -H 514 -i resources/how_generate_ethereum_wallet.mermaid -o resources/Figure1_Gen_Ethereum_Wallet.png
	mmdc -t forest -w 2080 -H 676 -i resources/magic_utc_file_pwd_to_priv.mermaid -o resources/Figure2_Magic_2FA_Get_PrivKey.png
	mmdc -t forest -w 2258 -H 2516 -i resources/how_generate_utc_file_simplified.mermaid -o resources/Figure3_Gen_Ethereum_UTC_JSON_File.png
