graph LR

Priv(Private Key: 256 bits)
Pwd(Password)
UTCFile(UTC JSON File)
Magic((Magic Happens Here))
Send((Send Viet 1,000,000 ETH))

Magic --> Priv;
UTCFile --> Magic;
Pwd --> Magic;
Priv --> Send;